### PR TITLE
adding contribution.md file to the repository

### PR DESCRIPTION
**Pull request by neutr0n420**

### CODE REVIEW

**Review by nicolasbock — CHANGES_REQUESTED** [review]
Thanks for submitting this PR @neutr0n420 !

Could you have a look at the linter issues (https://github.com/Temperate-Designs/platformer-1/pull/8/checks#step:4:8) and see whether you can fix them?

Thanks!

**Review by neutr0n420 — COMMENTED** [review]
I had changed the file can you please look into it

**Review by nicolasbock — CHANGES_REQUESTED** [review]
Thank you! This looks better already but there are still a few things the linter is complaining about:

https://github.com/Temperate-Designs/platformer-1/pull/8/checks#step:4:8

**Comment by nicolasbock** [comment]
@neutr0n420 Let me know if you need any help with fixing the linter issues.

**Comment by neutr0n420** [comment]
> @neutr0n420 Let me know if you need any help with fixing the linter issues.

Hey @nicolasbock some of the linter test are bothering me I do think that the contribution file will not look good according to this convention can you suggest something on it?
Screenshot 2022-10-09 at 12 25 17 AM

**Comment by nicolasbock** [comment]
The markdown will be rendered so that paragraphs will show with longer lines again. It's kind of like html.

**Comment by nicolasbock** [comment]
Hi @neutr0n420 

Do you need any help with reformatting the file?

**Comment by neutr0n420** [comment]
> Hi @neutr0n420
> 
> Do you need any help with reformatting the file?

Actually yes need some help can't able to figure it out on my own

**Review by nicolasbock — APPROVED** [review]
Thanks @neutr0n420 !

**Pull request merged**
